### ISSUE TITLE
Fortran testing framework needs to report errors from PIO_finalize

### ISSUE THREAD

**Issue by jayeshkrishna** [ACME-Climate/ParallelIO#50]
The fortran testing framework currently does not report errors during
PIO_finalize().

**Comment by jayeshkrishna** [comment]
After looking at the GPTL code it looks like the most frequent errors that we see with timers that are not closed in PIO (e.g. "newchild: child PIO:PIOc_closefile can't be a parent of itself") is ignored by  the GPTL library. The functions used to write GPTL logs don't return an error for these cases (just print these error messages to stdout).

So I am inclined to close this issue without fixing it. @dqwu : thoughts?

The following branch contains all the changes that was outlined in this issue (but the tests don't fail because GPTL internally ignores these errors) - https://github.com/ACME-Climate/ParallelIO/tree/jayeshkrishna/tf_ret_err_on_finalize

**Comment by worleyph** [comment]
The parent/child logic is used to determine how to set indentation for the per-process timing data output.

**Comment by dqwu** [comment]
@jayeshkrishna 
I think we can close this issue for now.

**Comment by jayeshkrishna** [comment]
Thanks @worleyph and @dqwu .
So the error messages are displayed when the GPTL library tries to construct the necessary internal data structures to print the collected timing data. The error messages are an indication of errors in the collected timing data (due to timers that are not closed) but the functions that log the timing data print error messages and continue (most likely to be resilient to minor errors in the timing data).

**Comment by worleyph** [comment]
Well the timing data is likely to be bogus. If you care about that, you should stop the timers. Since this only happens at failure, then the perturbation may be slight? Also, if you are using the standard GPTL release, I thought that it did not like "finishing" with running timers. Perhaps the feature to not complain has been implemented in the release version.

**Comment by jayeshkrishna** [comment]
I wanted a way to capture that the timing data logged by GPTL had errors in it. The GPTL functions that write log files (and GPTLfinalize) returned successfully for tests with timers that were not stopped.
Although the error messages themselves were not useful a simple debugging of the GPTL library showed me the timers that were at fault.
