### ISSUE TITLE
Do not silently open a file in a different format

### ISSUE THREAD

**Issue by rljacob** [ACME-Climate/ParallelIO#63]
Discussion in E3SM issue https://github.com/ACME-Climate/ACME/issues/2048 revealed that if PIO is told to open a file with pnetcdf and it can't, it will try Netcdf4P without notifying the user.

This could lead to difficult-to-track performance and useability issues if the Netcdf4P read works while the user thinks its Pnetcdf doing the work.

Output a warning message if the file is opened in a different format from what the user specified.

**Comment by jayeshkrishna** [comment]
PIO2 does even worse than PIO1, it tries to reopen the file with NetCDF (not NetCDF4P). There is some log message there (not useful at all) and needs to be modified to indicate the user of the behaviour.

**Comment by jayeshkrishna** [comment]
We need to add appropriate log messages to,
* PIO1 (pio1_0)
* PIO2 (master)

**Comment by jayeshkrishna** [comment]
The changes have been merged in PR #82 and PR #83
