### ISSUE TITLE
Use bget only for caching user data

### ISSUE THREAD

**Issue by jayeshkrishna** [ACME-Climate/ParallelIO#89]
The write multi buffer is a regular structure used in PIO2 and needs
to be allocated using calloc()/malloc() instead of bget (used to manage
cached user data, fillvalues etc).

The write multi buffer also contains a list of variables ids and frame 
numbers and also need to be allocated using realloc() instead of bgetr().

The change to use bget() to allocate the write multi buffer was added in
061ddfd4.

**Comment by jayeshkrishna** [comment]
@dqwu : Any thoughts?

**Comment by dqwu** [comment]
@jayeshkrishna 
One possible advantage to use bget for write multi buffer is that bget provides basic memory statistics (issue #87 is to add this feature when PIO_USE_MALLOC is ON).

**Comment by jayeshkrishna** [comment]
The current code uses statistics from bget to decide whether to flush cached user data. So using bget() to allocate other structures (assuming these are not big mem allocations) may complicate the logic. Note that PIO currently uses malloc/calloc to allocate memory for other data structures in the code.

**Comment by dqwu** [comment]
@jayeshkrishna 
Then we should use malloc/calloc for the write multi buffer.
We also need to check the PIO2 code to see if bget() is incorrectly used in other places.

**Comment by jayeshkrishna** [comment]
@dqwu : I just updated the issue to cover all instances in the code where bget* is used to allocate simple data structures (not related to caching user data)
